apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: urban-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
              name: external
            - containerPort: 29092
              name: internal
          envFrom:
            - configMapRef:
                name: kafka-config
